site_name: Opentrons API Docs

theme:
  name: material
  logo: assets/opentrons_logo_drop.png
  palette:
    scheme: preference
    primary: blue
    accent: light blue
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra:
  disqus: ot-docs

markdown_extensions:
- attr_list
- pymdownx.tabbed
- pymdownx.superfences
- admonition
- pymdownx.highlight:
    use_pygments: true
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# enables the custom OT icon but slows rebuild to 1m or so, disable for testing
      options:
        custom_icons:
          - overrides/.icons
- toc:
    permalink: true
- markdown_include.include

# see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
nav:
  - Getting Started :
    - Introduction : index.md
    - Some Python Basics : writing.md
    - Simulating Protocols: 
      - simulating.md
      - simulate_with_jupyter.md
    - Writing Your First Protocol : get_started.md
  - Hardware :
    - Opentrons Hardware: hardware.md
    - Pipettes : 
      - new_pipette.md
      - pipettes/behaviors.md
      - pipettes/defaults.md
    - Labware : 
      - new_labware.md
      - labware/accessing.md
      - labware/positioning.md
    - Modules :
      - new_modules.md
      - modules/temperature.md
      - modules/magnet.md
      - modules/thermocycler.md
  - Liquid Handling :
    - Using the API : using_the_api.md
    - Building Block Commands : 
      - new_atomic_commands.md
      - building_block/tip_handling.md
      - building_block/liquid_control.md
      - building_block/utility.md
    - Complex Commands : 
      - new_complex_commands.md
      - complex/transfer.md
      - complex/distribute_consolidate.md
      - complex/shared_parameters.md
    - Examples : 
      - examples/basic_transfer.md
      - examples/dilution.md
      - examples/loops.md
      - examples/multiple_air_gaps.md
      - examples/plate_mapping.md
  - Advanced Usage :
    - Introduction: new_examples.md 
    - Tips & Tricks:
      - examples/replace_tips.md
      - examples/is_simulating.md
      - examples/blink_lights.md
      - examples/liquid_level.md
    - Data & Device Management:
      - examples/ssh.md
      - examples/scp.md
      - examples/csv.md
      - examples/install_module.md
    - Running Without the App :
      - new_advanced_running.md
      - examples/jupyter_notebook.md
      - examples/command_line.md
      - examples/calibration.md
      - examples/integrating.md
    - Understanding the OT-2 Architecture: examples/architecture.md
  - API Reference : 
    - API Version 2 Reference: new_protocol_api.md
    - Versioning : versioning.md

repo_url: https://github.com/nickcrider/ot-docs
