name: Vale
on:
  push:
    branches: 
      - test-vale

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
