name: Proofread with Vale
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        files: docs
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
